### ISSUE TITLE
Cybox 2.0 support?

### ISSUE THREAD

**Issue by chrisfry** [stephenbrannon/IOCextractor#16]
Any plans to update the cybox export to v2?
http://cybox.mitre.org/language/version2.0/

**Comment by bworrell** [comment]
Hey @chrisfry! I just issued a pull request (https://github.com/stephenbrannon/IOCextractor/pull/17) for supporting CybOX v2.0. My pull request requires users to install [python-cybox v2.0.0](https://pypi.python.org/pypi/cybox/2.0.0) for the export of CybOX v2.0. Hopefully there aren't any issues and it can be merged soon :)

**Comment by stephenbrannon** [comment]
@chrisfry, I just merged @bworrell's pull request, so the new version should be ready to download. If there's any problem with installing python-cybox, the accompanying zip file has a .exe version that includes the update as well.
