### ISSUE TITLE
Non-ASCII Quotation line 58

### ISSUE THREAD

**Issue by n3l5** [stephenbrannon/IOCextractor#4]
Looks like a non-ascii quotation on line 58

**Comment by stephenbrannon** [comment]
Any chance you tried to run IOCextractor with Python 2? It's designed for Python 3 where the default encoding for source files is UTF-8 (see http://www.python.org/dev/peps/pep-3120/ or a longer discussion at http://docs.python.org/3.0/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit). If you're using Python 3, please let me know which distribution and OS, and I'll try to duplicate the error.

**Comment by n3l5** [comment]
Doh! You'd be right...guess I got my machines mixed up. Consider this closed on part of some sillyness. 

Thx for your work.
